// Generic CDP (V8) per-test coverage injection for ANY Playwright project.
//
// Real projects rarely ship istanbul per-test coverage. But Playwright's
// page.coverage (Chrome DevTools Protocol V8 coverage) records, per page,
// which served JS executed -- with NO build instrumentation. We "inject" a
// thin fixture that wraps page.coverage and writes, per test, the set of
// executed source files (the `json:files` layout that loadCovLive reads),
// then codemod the project's spec imports to use that fixture instead of
// '@playwright/test'. Business code is never modified.
//
// This module holds the PURE, unit-tested pieces; engine.mjs drives the IO.
import path from 'node:path';

const SRC_EXT = '(?:jsx?|tsx?|mjs|cjs)';
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// last path segment of a (possibly nested) srcGlob, e.g. 'apps/x/src' -> 'src'.
export function srcLeaf(srcGlob = 'src') {
  const parts = String(srcGlob).split('/').filter(Boolean);
  return parts.length ? parts[parts.length - 1] : 'src';
}

// Map a served JS URL to a LEAF-relative source path, or null. Anchored at the
// dev-server ORIGIN root so cross-package /@fs/.../src, /node_modules and
// /.vite/deps are excluded (they are not served at the app's own /<leaf>/ root).
// 'http://localhost:5173/src/a.tsx?t=1' --(leaf=src)--> 'src/a.tsx'
export function cdpUrlToLeafRel(url, leaf = 'src') {
  const p = String(url || '').split(/[?#]/)[0];
  if (!p) return null;
  const auth = p.match(/^[a-zA-Z][\w+.-]*:\/\/[^/]+(\/.*)$/);
  const pathPart = auth ? auth[1] : (p.startsWith('/') ? p : '/' + p);
  const m = pathPart.match(new RegExp(`^/(${escapeRe(leaf)}/[^?#]*\\.${SRC_EXT})$`));
  return m ? m[1] : null;
}

// The leaf regex used inside the injected fixture (origin-root anchored).
const fixtureLeafRe = (leaf) => `/^https?:\\/\\/[^/]+\\/(${escapeRe(leaf)}\\/[^?#]*\\.${SRC_EXT})(?:[?#]|$)/`;

// Re-attach the srcGlob prefix the leaf-relative path dropped, so coverage
// shares the same namespace as `git diff` paths (repo-root relative).
// srcGlob='src' -> 'src/a.tsx'; srcGlob='apps/x/src' -> 'apps/x/src/a.tsx'.
export function mapLeafRelToRepoRel(leafRel, srcGlob = 'src') {
  const leaf = srcLeaf(srcGlob);
  const prefix = String(srcGlob).slice(0, String(srcGlob).length - leaf.length);
  return prefix + leafRel;
}

// Rewrite `from '@playwright/test'` import specifiers to a local fixture path.
export function rewriteSpecImport(code, importSpec) {
  return rewriteImportFrom(code, ['@playwright/test'], importSpec);
}

// Generic: redirect `from '<one of fromSpecs>'` import sources to newSpec.
export function rewriteImportFrom(code, fromSpecs, newSpec) {
  let out = String(code);
  for (const from of fromSpecs) {
    const re = new RegExp(`(from\\s*['"])${escapeRe(from)}(['"])`, 'g');
    out = out.replace(re, `$1${newSpec}$2`);
  }
  return { code: out, changed: out !== code };
}

// POSIX relative import (no extension) from a spec file to the fixture file.
export function relImportPath(specAbs, fixtureAbs) {
  const toPosix = (s) => s.split(path.sep).join('/');
  let rel = path.posix.relative(path.posix.dirname(toPosix(specAbs)), toPosix(fixtureAbs));
  rel = rel.replace(/\.[mc]?[jt]sx?$/, '');
  return rel.startsWith('.') ? rel : './' + rel;
}

// The injected fixture source (TS). Re-exports everything from
// '@playwright/test' but overrides `test` with a coverage-collecting variant.
export function covFixtureSource(leaf = 'src') {
  return `// AUTO-GENERATED by covinject — CDP per-test coverage. Do not edit.
import { test as base } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
export * from '@playwright/test';

const OUT = process.env.COV_OUT || 'cov_pertest';
const RE = ${fixtureLeafRe(leaf)};

export const test = base.extend({
  page: async ({ page }, use, testInfo) => {
    try { await page.coverage.startJSCoverage({ resetOnNavigation: false }); } catch {}
    await use(page);
    let entries: any[] = [];
    try { entries = await page.coverage.stopJSCoverage(); } catch {}
    const files = new Set<string>();
    for (const e of entries) {
      const m = String(e.url || '').match(RE);
      if (!m) continue;
      const hit = (e.functions || []).some((fn: any) => (fn.ranges || []).some((r: any) => r.count > 0));
      if (hit) files.add(m[1]);
    }
    fs.mkdirSync(OUT, { recursive: true });
    const id = testInfo.titlePath.join(' > ');
    fs.writeFileSync(path.join(OUT, id.replace(/[^\\w.-]+/g, '_') + '.json'),
      JSON.stringify({ test: id, files: [...files].sort() }));
  },
});
`;
}

// Variant for projects whose specs import { test, expect } from a custom
// fixtures module and create pages via `browser.newPage()` (so the page
// fixture is bypassed). We re-export their test, wrapped with an auto fixture
// that hooks browser.newPage per test to start coverage and collects at end.
export function covWrapFixtureSource(leaf = 'src', appImport = './fixtures') {
  return `// AUTO-GENERATED by covinject — CDP per-test coverage (newPage wrap). Do not edit.
import { test as appTest, expect } from '${appImport}';
import fs from 'node:fs';
import path from 'node:path';
export { expect };

const OUT = process.env.COV_OUT || 'cov_pertest';
const RE = ${fixtureLeafRe(leaf)};

export const test = appTest.extend<{ _cov: void }>({
  _cov: [async ({ browser }, use, testInfo) => {
    const orig = browser.newPage.bind(browser);
    const files = new Set<string>();
    const seen = new Set<string>();
    const pending = new Set<any>();
    const collect = async (p: any) => {
      if (!pending.has(p)) return;
      pending.delete(p);
      let entries: any[] = [];
      try { entries = await p.coverage.stopJSCoverage(); } catch {}
      for (const e of entries) {
        const url = String(e.url || '');
        if (process.env.COV_DEBUG) seen.add(url);
        const m = url.match(RE);
        if (!m) continue;
        const hit = (e.functions || []).some((fn: any) => (fn.ranges || []).some((r: any) => r.count > 0));
        if (hit) files.add(m[1]);
      }
    };
    (browser as any).newPage = async (o: any) => {
      const p = await orig(o);
      try { await p.coverage.startJSCoverage({ resetOnNavigation: false }); } catch {}
      pending.add(p);
      const origClose = p.close.bind(p);  // collect BEFORE the test closes the page
      p.close = async (...args: any[]) => { await collect(p); return origClose(...args); };
      return p;
    };
    await use();
    (browser as any).newPage = orig;
    for (const p of [...pending]) await collect(p);
    fs.mkdirSync(OUT, { recursive: true });
    const id = testInfo.titlePath.join(' > ');
    fs.writeFileSync(path.join(OUT, id.replace(/[^\\w.-]+/g, '_') + '.json'),
      JSON.stringify({ test: id, files: [...files].sort() }));
    if (process.env.COV_DEBUG) fs.writeFileSync(path.join(OUT, '_urls.json'), JSON.stringify([...seen].slice(0, 60), null, 2));
  }, { auto: true }],
});
`;
}
