// Generic CDP (V8) per-test coverage injection for ANY Playwright project.
//
// Real projects rarely ship istanbul per-test coverage. But Playwright's
// page.coverage (Chrome DevTools Protocol V8 coverage) records, per page,
// which served JS executed -- with NO build instrumentation. We "inject" a
// thin fixture that wraps page.coverage and writes, per test, the set of
// executed source files (the `json:files` layout that loadCovLive reads),
// then codemod the project's spec imports to use that fixture instead of
// '@playwright/test'. Business code is never modified.
//
// This module holds the PURE, unit-tested pieces; engine.mjs drives the IO.
import path from 'node:path';

const SRC_EXT = '(?:jsx?|tsx?|mjs|cjs)';
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// last path segment of a (possibly nested) srcGlob, e.g. 'apps/x/src' -> 'src'.
export function srcLeaf(srcGlob = 'src') {
  const parts = String(srcGlob).split('/').filter(Boolean);
  return parts.length ? parts[parts.length - 1] : 'src';
}

// Map a served JS URL to a LEAF-relative source path, or null. Skips deps.
// 'http://localhost:5173/src/a.tsx?t=1' --(leaf=src)--> 'src/a.tsx'
export function cdpUrlToLeafRel(url, leaf = 'src') {
  const p = String(url || '').split(/[?#]/)[0];
  if (!p || p.includes('node_modules') || p.includes('/.vite/') || p.includes('/@')) return null;
  const m = p.match(new RegExp(`/(${escapeRe(leaf)}/[^?#]*\\.${SRC_EXT})$`));
  return m ? m[1] : null;
}

// Re-attach the srcGlob prefix the leaf-relative path dropped, so coverage
// shares the same namespace as `git diff` paths (repo-root relative).
// srcGlob='src' -> 'src/a.tsx'; srcGlob='apps/x/src' -> 'apps/x/src/a.tsx'.
export function mapLeafRelToRepoRel(leafRel, srcGlob = 'src') {
  const leaf = srcLeaf(srcGlob);
  const prefix = String(srcGlob).slice(0, String(srcGlob).length - leaf.length);
  return prefix + leafRel;
}

// Rewrite `from '@playwright/test'` import specifiers to a local fixture path.
export function rewriteSpecImport(code, importSpec) {
  const re = /(from\s*['"])@playwright\/test(['"])/g;
  const out = String(code).replace(re, `$1${importSpec}$2`);
  return { code: out, changed: out !== code };
}

// POSIX relative import (no extension) from a spec file to the fixture file.
export function relImportPath(specAbs, fixtureAbs) {
  const toPosix = (s) => s.split(path.sep).join('/');
  let rel = path.posix.relative(path.posix.dirname(toPosix(specAbs)), toPosix(fixtureAbs));
  rel = rel.replace(/\.[mc]?[jt]sx?$/, '');
  return rel.startsWith('.') ? rel : './' + rel;
}

// The injected fixture source (TS). Re-exports everything from
// '@playwright/test' but overrides `test` with a coverage-collecting variant.
export function covFixtureSource(leaf = 'src') {
  return `// AUTO-GENERATED by covinject — CDP per-test coverage. Do not edit.
import { test as base } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
export * from '@playwright/test';

const OUT = process.env.COV_OUT || 'cov_pertest';
const RE = /\\/(${escapeRe(leaf)}\\/[^?#]*\\.${SRC_EXT})(?:[?#]|$)/;

export const test = base.extend({
  page: async ({ page }, use, testInfo) => {
    try { await page.coverage.startJSCoverage({ resetOnNavigation: false }); } catch {}
    await use(page);
    let entries: any[] = [];
    try { entries = await page.coverage.stopJSCoverage(); } catch {}
    const files = new Set<string>();
    for (const e of entries) {
      const m = String(e.url || '').match(RE);
      if (!m) continue;
      const hit = (e.functions || []).some((fn: any) => (fn.ranges || []).some((r: any) => r.count > 0));
      if (hit) files.add(m[1]);
    }
    fs.mkdirSync(OUT, { recursive: true });
    const id = testInfo.titlePath.join(' > ');
    fs.writeFileSync(path.join(OUT, id.replace(/[^\\w.-]+/g, '_') + '.json'),
      JSON.stringify({ test: id, files: [...files].sort() }));
  },
});
`;
}
